# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0678ac2926fd0e66aa05259d5067150f26d89e57c0b323dd8532861e5dc8ee3e103d816ac140f44c34a71c8feaa55a213d51c71aada5489d905dff58041f103b

test:
  secret_key_base: 83778d15b8020080e7e0154a2473d919d7a999f6e7b2bea383673b703e2f7ed8ea275a07738dd2d57c9e6491a664834dc8b17708108302804f1a98185ceebe37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
